FROM apache/spark:3.5.1

USER root

# Python dependencies
RUN pip install --no-cache-dir \
    numpy \
    pandas \
    pyarrow \
    scikit-learn \
    pillow

# Make sure Spark uses python3 consistently
ENV PYSPARK_PYTHON=python3